### ISSUE TITLE
关于“指定日期节假日信息”接口问题

### ISSUE THREAD

**Issue by mmmcctvcn** [MZCretin/RollToolsApi#10]
hello，首先感谢提供这么好用的接口，我有用“http://www.mxnzp.com/api/holiday/list/month”接口做了一个自动生成考勤表的软件，这样我们几个同事就不用每次去打卡，再导出打卡数据了，但是目前发现有几个日期的数据有点问题。具体是：20190427，应该是休息日，结果返回的是工作日，20190429应该是工作日，结果返回的是劳动节，20190430应该是工作日，结果返回的是劳动节，不知道是否有空帮忙把数据修复一下？这样我就不用手工做表了，哈哈

**Comment by MZCretin** [comment]
好的 我去看下
 @mmmcctvcn

**Comment by MZCretin** [comment]
已处理 @mmmcctvcn
