### ISSUE TITLE
NoTitle

### ISSUE THREAD

**Issue by cllstudy** [MZCretin/RollToolsApi#11]
我有世界国家城市信息的json和世界国家电话区号json,如果可以转换为接口,我可以为您提供json文件

**Comment by MZCretin** [comment]
@cllstudy 数据准确性高嘛？可以的哦  哈哈哈

**Comment by cllstudy** [comment]
世界国家是从QQ上爬的 世界区号是钉钉上的
[电话区号]https://www.cllhui.cn/data/telephone.json)
[世界国家](https://www.cllhui.cn/data/city.json)

您可以看看先

**Comment by cllstudy** [comment]
hot字段是热门城市

**Comment by MZCretin** [comment]
好的 我先看看  然后抽空加到接口去呢  谢谢 哈哈哈 @cllstudy

**Comment by cllstudy** [comment]
恩恩 不客气 个人感觉这个项目还是非常有用的 给你的两个json我也是因为项目需要找半天.至此,这个issue将被关闭

**Comment by MZCretin** [comment]
@cllstudy  已添加到接口中 感谢
