### ISSUE TITLE
想看下源码

### ISSUE THREAD

**Issue by oweson** [MZCretin/RollToolsApi#13]
觉得你挺厉害的！想看下源码不知道可以不

**Comment by MZCretin** [comment]
这个项目目前只开放了一部分的接口  主要接口是在服务我的一款app 所以不方便开源

**Comment by oweson** [comment]
没事啦，你很优秀😄


 
---原始邮件---
发件人: "穆仙念"<notifications@github.com>
发送时间: 2019年6月1日(星期六) 晚上8:51
收件人: "MZCretin/RollToolsApi"<RollToolsApi@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"皮皮程"<570347720@QQ.com>;
主题: Re: [MZCretin/RollToolsApi] 想看下源码 (#13)



这个项目目前只开放了一部分的接口  主要接口是在服务我的一款app 所以不方便开源
