### ISSUE TITLE
万年历20190929号type类型错误

### ISSUE THREAD

**Issue by cfengdev** [MZCretin/RollToolsApi#18]
https://www.mxnzp.com/api/holiday/single/20190929

{
code: 1,
msg: "数据返回成功",
data: {
date: "2019-09-29",
weekDay: 7,
yearTips: "己亥",
type: 1,
typeDes: "工作日",
chineseZodiac: "猪",
solarTerms: "秋分后",
avoid: "定磉.安葬",
lunarCalendar: "九月初一",
suit: "祭祀.赴任.动土.上梁.开光.塑绘.冠笄.拆卸.起基.安床.开市.立券.赴任.经络",
dayOfYear: 272,
weekOfYear: 39,
constellation: "天秤座"
}
}

type 应该是0吧

**Comment by MZCretin** [comment]
@cfengdev  已修复
