### ISSUE TITLE
发现两个获取北京时间的

### ISSUE THREAD

**Issue by cllstudy** [MZCretin/RollToolsApi#19]
淘宝：http://api.m.taobao.com/rest/api3.do?api=mtop.common.getTimestamp

苏宁：http://quan.suning.com/getSysTime.do

这个issues提交的目的只是为了以后查询方便,您也可以做成自己的接口,当然,也可以直接使用该接口,

**Comment by MZCretin** [comment]
后面会添加一个获取服务器时间的接口

**Comment by MZCretin** [comment]
@cllstudy 已新增接口，请查阅文档 https://github.com/MZCretin/RollToolsApi#%E8%8E%B7%E5%8F%96%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%97%B6%E9%97%B4
