### ISSUE TITLE
万年历-指定日期查询

### ISSUE THREAD

**Issue by Coderzhong** [MZCretin/RollToolsApi#23]

**Comment by MZCretin** [comment]
https://github.com/MZCretin/RollToolsApi#%E6%8C%87%E5%AE%9A%E6%97%A5%E6%9C%9F%E7%9A%84%E8%8A%82%E5%81%87%E6%97%A5%E5%8F%8A%E4%B8%87%E5%B9%B4%E5%8E%86%E4%BF%A1%E6%81%AF

@Coderzhong

**Comment by Coderzhong** [comment]
你好，我在调用万年历-指定日期查询接口的时候，只能查2002年-2019年之间的数据，该范围之前和之后的返回数据信息如下：
![image](https://user-images.githubusercontent.com/24318123/61786591-a0c64880-ae40-11e9-9a0a-6982d1cde8b5.png)
![image](https://user-images.githubusercontent.com/24318123/61786638-b6d40900-ae40-11e9-9d90-8d0591ae7611.png)

**Comment by brokrechen** [comment]
你应该找原作者，这只是我克隆过来的项目

 

 ------------------ 原始邮件 ------------------
  发件人: "Coderzhong"<notifications@github.com>;
 发送时间: 2019年7月24日(星期三) 晚上6:29
 收件人: "MZCretin/RollToolsApi"<RollToolsApi@noreply.github.com>;
 抄送: "Subscribed"<subscribed@noreply.github.com>;
 主题: Re: [MZCretin/RollToolsApi] 万年历-指定日期查询 (#23)

 

 
你好，我在调用万年历-指定日期查询接口的时候，只能查2002年-2019年之间的数据，该范围之前和之后的返回数据信息如下：

**Comment by Coderzhong** [comment]
@brokrechen 原作者该怎么联系啊

**Comment by brokrechen** [comment]
我看错了，我没克隆这项目，好像是stay或者watch，你怎么会发邮件发到我这边过来。。。。。
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Coderzhong"<notifications@github.com>;
 发送时间: 2019年7月24日(星期三) 晚上6:35
 收件人: "MZCretin/RollToolsApi"<RollToolsApi@noreply.github.com>;
 抄送: "."<723618372@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [MZCretin/RollToolsApi] 万年历-指定日期查询 (#23)

 

 
@brokrechen 原作者该怎么联系啊

**Comment by Coderzhong** [comment]
@brokrechen 我看到你在我提的issue下面回复了-。- 就艾特了你
