### ISSUE TITLE
调用万年历-指定日期查询接口的时候，只能查2002年-2019年范围之间的

### ISSUE THREAD

**Issue by Coderzhong** [MZCretin/RollToolsApi#24]
你好，我在调用万年历-指定日期查询接口的时候，只能查2002年-2019年之间的数据，该范围之前和之后的返回数据信息如下：
![image](https://user-images.githubusercontent.com/24318123/61786591-a0c64880-ae40-11e9-9a0a-6982d1cde8b5.png)
![image](https://user-images.githubusercontent.com/24318123/61786638-b6d40900-ae40-11e9-9d90-8d0591ae7611.png)

_Originally posted by @Coderzhong in https://github.com/MZCretin/RollToolsApi/issues/23#issuecomment-514576517_

**Comment by MZCretin** [comment]
你好，这是个节假日的接口，主要提供的是节假日的信息，附加一些万年历的功能！节假日在2002年之前国务院没有正式颁发过节假日声明，所以之前的数据没有。每年年初国家会出台本年度相关节假日的声明，所以数据截止于2019年！
