### ISSUE TITLE
关于笑话API的请求问题

### ISSUE THREAD

**Issue by SunRelease** [MZCretin/RollToolsApi#38]
大佬,您好,今天我用您的`jokes`接口时,出现了`小程序`请求返回`JSON`数据不一样.

- 比如在`PC`模拟端上请求全部正常:

![20200209162113](https://ae01.alicdn.com/kf/Hc0d42f460d41401fa0aa026ad5a4c051w.jpg)

![20200209163218](https://ae01.alicdn.com/kf/H01856bea42aa456ab5af664f68fc6eeay.jpg)
- 但是在`真机模拟`上,除了第一页是正常返回`JSON`格式外,后面`data`数据都多了个`""`双引号:

![20200209162407](https://ae01.alicdn.com/kf/H5a5a22e7fe324a42ac88b1a229605eccW.jpg)

>而且,我也使用`JSON.parse`尝试对其`data`解析,但是报错,当然,也是今天才出现这种情况,昨天都没有出现,我也参考了网上资料,也有类似的情况,不知道是什么问题呢?非常感谢您能提供这个机会给我们学习

[网上资料一](https://developers.weixin.qq.com/community/develop/doc/000046a32d43106dbfd78eaed56000?_at=1581234287004)
[网上资料二](http://www.wxapp-union.com/forum.php?mod=viewthread&tid=1522)

**Comment by MZCretin** [comment]
接口是没有问题的，是你自己的使用问题，请自行检查使用方式 @SunRelease
