### ISSUE TITLE
【根据新闻类型获取新闻列表】接口返回数据重复

### ISSUE THREAD

**Issue by senxiaoxing** [MZCretin/RollToolsApi#42]
https://www.mxnzp.com/api/news/list?typeId=521&page=1
当typeId=521，page大于2时，返回的都是重复的10条记录

**Comment by MZCretin** [comment]
会尽快修复

**Comment by MZCretin** [comment]
这个需要你本地做下过滤 数据也是抓取的 服务端不好判断是否是重复的
