### ISSUE TITLE
物流查询问题

### ISSUE THREAD

**Issue by MOldtime** [MZCretin/RollToolsApi#46]
`curl -X POST -H "Content-Type:application/x-www-form-urlencoded" -H "Content-Length:67" -H "Host:www.mxnzp.com" -H "Connection:Keep-Alive" -H "Accept-Encoding:gzip" -H "User-Agent:okhttp/3.11.0" -d 'app_id=pvgqxxxxxsdqr&app_secret=Vjk9xxxxxxxQT09' "https://www.mxnzp.com/api/logistics/details/search?logistics_no=557019329315102&logistics_id=2"`
无法获得响应结果 只能等待超时

**Comment by MZCretin** [comment]
此接口正在升级中
