### ISSUE TITLE
/holiday/single 接口502了

### ISSUE THREAD

**Issue by zhihuihu** [MZCretin/RollToolsApi#47]
https://www.mxnzp.com/api/holiday/single/20200819

![image](https://user-images.githubusercontent.com/16135245/90587552-3ed73e80-e20c-11ea-81af-0be03850a024.png)

**Comment by gd4Ark** [comment]
+1

**Comment by MZCretin** [comment]
@zhihuihu @gd4Ark 请求链接发出来看看
