### ISSUE TITLE
大乐透接口错误

### ISSUE THREAD

**Issue by cc1024** [MZCretin/RollToolsApi#52]
> https://www.mxnzp.com/api/lottery/common/latest?code=cjdlt&app_id=lqidsosftvksuimd&app_secret=aldsZ1NsQzJHcWpuSnBZVmFpLzhPQT09

返回 
> {"code":1,"msg":"数据返回成功！","data":{"openCode":"03,04,24,26,35+07+08","code":"cjdlt","expect":"2022058","name":"超级大乐透","time":"2022-05-25 20:30:00"}}

是5月25日的结果。

谢谢！

**Comment by MZCretin** [comment]
数据有点问题，已经修复

**Comment by cc1024** [comment]
神速 谢谢大佬
