### ISSUE TITLE
项目是不维护了吗？

### ISSUE THREAD

**Issue by myadmin** [MZCretin/RollToolsApi#60]
美女图片接口获取到的图片现在都是403了。。。
![image](https://user-images.githubusercontent.com/6794499/228285805-b9567673-d4bf-4a82-8797-1d721d05ef04.png)
![image](https://user-images.githubusercontent.com/6794499/228285875-604e6673-7703-44a1-a696-0b01453440ad.png)

**Comment by MZCretin** [comment]
是换成了资源更好的v2接口，但是不能放出来
