### ISSUE TITLE
双色球中奖计算好像有些问题

### ISSUE THREAD

**Issue by hcliu987** [MZCretin/RollToolsApi#61]
![image](https://github.com/MZCretin/RollToolsApi/assets/52879991/4aed3a3c-313f-4399-ada6-c81a0bf22312)
![image](https://github.com/MZCretin/RollToolsApi/assets/52879991/7ba3af65-89f4-44ec-9174-8f13643427ab)
全是蓝球吗

**Comment by nobugpy** [comment]
您好，您发给嘉伟的邮件已经收到。。。

**Comment by hcliu987** [comment]
改过了。原来最后一个 不是2位数要+0
