### ISSUE TITLE
感谢作者提供这么好用的接口，有个小问题想提下

### ISSUE THREAD

**Issue by jayZOU** [MZCretin/RollToolsApi#7]
2008年之前的数据好像都没有，这块能不能补下么？
`
curl http://www.mxnzp.com/api/holiday/list/year/2008

{"msg":"没有对应2008的列表节假日信息，请联系管理员","code":0}
`

**Comment by MZCretin** [comment]
@jayZOU  emmm 当时觉得提供到2010年就已经够久远了 哈哈  有空补上  等通知哦

**Comment by jayZOU** [comment]
@MZCretin 了解

**Comment by MZCretin** [comment]
@jayZOU 数据以及补充到2002年了，2002年之前的节假日信息国务院没有发布，不再做统计！
